import { describe, expect, it } from "vitest";
import { renderEldspireRules } from "./eldspire-rules";

describe("Eldspire rules", () => {
  it("renders the migrated rules and every d100 table", () => {
    const html = renderEldspireRules();

    expect(html).toContain("How To Play");
    expect(html).toContain('id="rolling"');
    expect(html).toContain('id="actions-threats"');
    expect(html).toContain('id="character-tables"');
    expect(html).not.toContain('href="/rules/variant"');
    expect(html).toContain("Actions describe practiced competence");
    expect(html).toContain("Assign seven starting Action points");
    expect(html).toContain("rate two Actions 2 and three Actions 1");
    expect(html).toContain("Every other Action is untrained and rated 0");
    expect(html).not.toContain("Choose one starting array");
    expect(html).not.toContain("<strong>Focused:</strong>");
    expect(html).not.toContain("<strong>Versatile:</strong>");
    expect(html).toContain("Monster Anatomy d10");
    expect(html).toContain("replaces one Action d6");
    expect(html).toContain("Highest is 1–3");
    expect(html).toContain("Highest is 4–5");
    expect(html).toContain("Two or more dice show 6+");
    expect(html).toContain("At Action 0, roll two dice and keep the lower");
    expect(html).toContain("Fatigue is a visible clock from 0–10");
    expect(html).toContain("Invoke</strong> rating equals or exceeds its Tier");
    expect(html).toContain("New Practiced Feature (d8)");
    expect(html).toContain("Conflict normally begins with what a character wants to change");
    expect(html).toContain("The normal rhythm:</strong> goal → opposition and stakes");
    expect(html).not.toContain("The GM announces threats; players describe how they answer");
    expect(html).not.toContain("Separate Fatigue Dice");
    expect(html).not.toContain("Deferred During This Playtest");
    expect(html).not.toContain("Situation die");
    expect(html).not.toContain("dynamic Difficulty");
    expect(html).not.toContain("position-and-effect");
    expect(html).not.toContain("Rally check");
    expect(html).not.toContain("Tier does not");
    expect(html).not.toContain("Experimental alternatives");
    expect(html).not.toContain("Adjudicating the Fiction");
    expect(html).not.toContain("The GM");
    expect(html).not.toContain("Lead and Spotlight");
    expect(html).not.toContain("When Opposition Leads");
    expect(html).not.toContain("Fatigue Floor");
    expect(html).not.toContain("Untreated Floor");
    expect(html).not.toContain("All Treated");
    expect(html).not.toContain("A good camp clears 3 Fatigue");
    expect(html).not.toContain("Highest is 1–4");
    expect(html).not.toContain("<strong>Fray.</strong>");
    expect(html).not.toContain("<strong>Faltering.</strong>");
    expect(html).not.toContain("Threat Format");
    expect(html).not.toContain("Threat Spark Tables");
    expect(html).not.toContain("{{table:");
    expect(html.match(/<tr><td>100<\/td>/g)).toHaveLength(9);
  });
});
