import { createFileRoute } from "@tanstack/solid-router";
import { createSignal, For } from "solid-js";

export const Route = createFileRoute("/generate/background")({
  component: BackgroundGenerator,
});

type TableId = "custom" | "shadowdark" | "diablerie" | "midnight-sun";

interface BackgroundTable {
  id: TableId;
  name: string;
  dieSize: number;
  backgrounds: string[];
}

const tables: BackgroundTable[] = [
  {
    id: "custom",
    name: "Custom",
    dieSize: 500,
    backgrounds: [
      // Original 100 backgrounds
      "Chimney sweep who learned to navigate cities entirely by rooftop",
      "Foundling raised by a temple as a living saint, paraded out for holy days",
      "Apprentice to a ratcatcher who cleared infestations from noble estates",
      "Child of traveling puppet-show performers, raised on the road",
      "Grew up in a lighthouse, seeing your keeper parent only during storms",
      "Tanner's assistant, forever marked by the smell of curing hides",
      "Ward of the state raised in a workhouse, learned to survive on scraps",
      "Mud lark who scavenged valuables from river banks and sewage outlets",
      "Raised in a monastery copying illuminated manuscripts in silence",
      "Child laborer in a textile mill, nimble fingers from working looms",
      "Offspring of a hangman, shunned by the community despite steady work",
      "Kitchen scullion in a noble house, invisible but overhearing everything",
      "Shepherd who spent years alone with flocks in mountain pastures",
      "Raised aboard a merchant vessel, never setting foot on land until adulthood",
      "Apprentice embalmer, preparing the wealthy dead for their final rest",
      "Street sweeper who kept the city's main thoroughfares clean for copper coins",
      "Child of a court astrologer, raised among star charts and nobles' anxieties",
      "Beggar's guild member, trained in the art of performative poverty",
      "Stablehand at a knight's estate, caring for warhorses worth more than your life",
      "Raised in a leper colony, immune but forever associated with the afflicted",
      "Falconer's apprentice, training hunting birds for aristocratic sport",
      "Child of a crime lord, raised in luxury built on suffering",
      "Indentured servant paying off a parent's debts through years of labor",
      "Raised by a village wise woman, learning herb-lore and folk remedies",
      "Quarry worker, cutting stone blocks from cliffsides since childhood",
      "Orphan adopted by a theatre troupe, playing children's roles until you aged out",
      "Toll bridge keeper's child, watching the world pass by but never joining it",
      "Apprentice to a forger, learning to replicate noble seals and signatures",
      "Pit fighter's child, raised in the bloody world of underground combat",
      "Runner for a gambling den, carrying messages and bribes across the city",
      "Foundry worker, pouring molten metal since your hands were big enough",
      "Raised as a food taster for a paranoid monarch",
      "Child of a sin-eater, watching your parent consume funeral meals to absolve the dead",
      "Trained from birth as a diplomatic hostage, ensuring your nation's good behavior",
      "Lamplighter's apprentice, knowing every dark corner of the city streets",
      "Raised by a reclusive scholar, your only companions being books and silence",
      "Gravedigger's child, playing among headstones and helping with burials",
      "Dockworker who loaded and unloaded cargo from across the known world",
      "Raised in a traveling circus, performing acrobatics before you could read",
      "Child of a professional duelist, learning swordplay as others learned letters",
      "Serving girl at a crossroads inn, hearing every traveler's tale",
      "Charcoal burner's apprentice, living in forest camps for months at a time",
      "Raised in a gladiatorial school as future arena entertainment",
      "Leech collector, wading through swamps gathering medicinal bloodsuckers",
      "Child of a counterfeiter, learning to spot fake coins before real ones",
      "Raised among nomadic horse traders, never staying anywhere longer than a season",
      "Apprentice to a torturer, learning anatomy through cruelty",
      "Powder monkey on a warship, carrying ammunition during naval battles",
      "Raised in a brothel, learning to read people's desires and deceptions",
      "Fence's runner, moving stolen goods between thieves and buyers",
      "Child of a monster hunter, raised on campfire tales of creatures slain",
      "Trained as a food taster for a merchant caravan crossing hostile lands",
      "Raised by an exiled noble, learning courtly manners in poverty",
      "Apprentice chandler, making candles and soap from rendered fat",
      "Child soldier conscripted during a border war, surviving against odds",
      "Raised in a debtor's prison alongside an incarcerated parent",
      "Pearl diver, plunging into cold waters since childhood for wealthy patrons",
      "Messenger runner for a merchant guild, memorizing routes and faces",
      "Raised by retired adventurers, hearing stories of dungeons and glory",
      "Apprentice to a siege engineer, learning to build and break fortifications",
      "Child of a smuggler, learning secret routes and hidden coves",
      "Raised in an asylum as the child of a patient, normalized to madness",
      "Barber-surgeon's apprentice, learning to cut hair and amputate limbs",
      "Trained as a court page, fetching and carrying for nobility",
      "Raised by a mute hermit in the wilderness, learning to communicate without words",
      "Apprentice matchmaker, studying bloodlines and negotiating marriages",
      "Child of a tax collector, despised wherever your family traveled",
      "Raised in a salt mine, never seeing daylight for years at a time",
      "Trained as a perfumer's assistant, developing an exceptional sense of smell",
      "Child of refugees, constantly fleeing from one war to the next",
      "Kennel keeper for hunting dogs, understanding animals better than people",
      "Raised by a disgraced knight, trained for glory you could never claim",
      "Apprentice to a money lender, learning to calculate interest and assess risk",
      "Child of a cult leader, raised believing your parent was divine",
      "Trained as a scribe's assistant, copying legal documents and contracts",
      "Raised on a prison hulk, a decommissioned ship housing criminals",
      "Dye worker's child, permanently stained from handling pigments",
      "Trained as a herald, memorizing noble lineages and heraldic symbols",
      "Raised in a colony for the criminally insane as staff family",
      "Apprentice to a fireworks maker, learning to work with volatile materials",
      "Child of a body snatcher, procuring corpses for medical schools",
      "Raised among a clan of professional tomb raiders",
      "Trained as a professional food tester at a wizards' academy",
      "Raised by a blind seer, learning to navigate the world as their eyes",
      "Apprentice to a pawnbroker, learning the value and history of objects",
      "Child of a spy, raised with multiple identities and no true name",
      "Trained as a professional witness, paid to observe and testify",
      "Raised in a menagerie caring for exotic beasts from distant lands",
      "Apprentice to a map-maker, learning geography through illustration",
      "Child of a bridge builder, traveling from project to project",
      "Trained as a poison tester for an assassins' guild",
      "Raised by a vocal teacher, trained to sing before nobility",
      "Apprentice to a locksmith, learning every mechanism that keeps things secure",
      "Child raised in a hospital for incurable diseases, constantly surrounded by death",
      "Trained as a sommelier's assistant, developing a refined palate",
      "Raised as the companion to a sickly noble child, educated above your station",
      "Apprentice to a glassblower, creating delicate works in searing heat",
      "Child of an informant, learning that everyone has secrets worth selling",
      "Trained as a professional mourner, weeping at strangers' funerals",
      "Raised in a dragon cult, taught to worship the great wyrms as gods",
      // Second 100 backgrounds
      "Raised by a traveling puppeteer who used you as an unwitting accomplice in cons",
  "Survived three days trapped in a collapsed mine, conversing with something in the dark",
  "Former taster for a paranoid noble—you've built up immunity to seventeen poisons",
  "Grew up in a lighthouse where ships kept wrecking despite your family's diligence",
  "Apprenticed to a cartographer who mapped places that don't exist yet",
  "Escaped a monastery after discovering what the brothers were really brewing",
  "Worked the graveyard shift at a morgue where bodies occasionally sat up to chat",
  "Raised as the designated heir to a throne that was abolished before you came of age",
  "Spent a year living feral in the woods after your caravan was ambushed—you remember little",
  "Former professional mourner, hired to weep at rich strangers' funerals",
  "Grew up backstage at an opera house, raised collectively by the company",
  "Survived being sacrificed—the god apparently found you unacceptable",
  "Trained from childhood to impersonate a specific noble's deceased child",
  "Worked as a rat-catcher in a city where the rats were organized",
  "Raised in a prison, child of a lifer who taught you everything about crime except how to avoid capture",
  "Former member of a doomsday cult—the world didn't end, so you left",
  "Apprenticed to a dentist who extracted more than teeth",
  "Grew up on a ship that never docked in the same port twice",
  "Raised by your grandparent who claimed to be over 300 years old—and had documentation",
  "Worked as a food taster for an executioner who took pride in last meals",
  "Survived a plague that killed everyone else in your village—they blame you",
  "Former stablehand at a facility that bred something other than horses",
  "Raised in a library by scholars who treated you as a research subject",
  "Spent your youth as a mudlark, finding strange things in river muck",
  "Trained as a sin-eater, consuming ritual meals over corpses to absorb their transgressions",
  "Grew up in a border town that changed nations seven times before you turned fifteen",
  "Former assistant to an anatomist who sourced specimens questionably",
  "Raised by a hermit who turned out to be hiding from something that eventually found them",
  "Worked as a chimney sweep in a city of ancient towers with non-standard architecture",
  "Survivor of a shipwreck who washed ashore somewhere that isn't on any map",
  "Raised in a workhouse that manufactured items you weren't allowed to examine closely",
  "Former keeper of a menagerie of creatures that no longer exist",
  "Grew up as the designated bad-luck-absorber for a superstitious noble family",
  "Apprenticed to a bell-maker whose bells had unusual acoustic properties",
  "Raised in a town that only appears on certain nights of the year",
  "Worked as a professional dreamer, paid to sleep in haunted places",
  "Former assistant to a portrait painter whose subjects kept dying shortly after sitting",
  "Raised by a parent who was slowly transforming into something else",
  "Grew up maintaining the clockwork mechanisms beneath a major city",
  "Survivor of a boarding school where students kept graduating under mysterious circumstances",
  "Raised as a 'lucky child' kept in a casino to influence fortune",
  "Former messenger who carried letters between parties in a generations-long blood feud",
  "Apprenticed to a perfumer who could bottle emotions",
  "Grew up in the shadow of a massive statue that everyone pretended not to see",
  "Worked as a translator for diplomats from a nation nobody else remembers existing",
  "Raised in a family of generational servants to an empty house, maintaining it for masters who never came",
  "Former keeper of a toll bridge over a river that sometimes flowed uphill",
  "Grew up in a foundling home sponsored by a guild with ulterior motives",
  "Survived being 'adopted' by fae for several years—time moved differently there",
  "Raised as a living reference in a forger's workshop, your handwriting copied for documents",
  "Former attendant at bathhouses where the elite discussed things they shouldn't have in front of you",
  "Apprenticed to a glassblower who trapped things inside the glass",
  "Raised in a salt mine where the walls whispered advice",
  "Worked as a night-soil collector who found valuables in the refuse",
  "Grew up in a traveling circus as the person who cared for the animal that wasn't an animal",
  "Former scribe for a judge who handed down sentences based on criteria you never understood",
  "Raised by a retired adventurer who trained you obsessively for a threat they wouldn't name",
  "Survived an avalanche and walked out of the mountains two years later with no memory of the interval",
  "Apprenticed to a chandler whose candles showed different things when lit",
  "Grew up as the companion-servant to a noble child who wasn't entirely human",
  "Former lamplighter in a city where certain streets must never go dark",
  "Raised in a village that paid annual tribute to the forest—you were almost the payment once",
  "Worked as a code-runner for revolutionaries, memorizing messages you didn't understand",
  "Grew up in a family of masons who built secret rooms into every structure",
  "Former assistant to a taxidermist with an unusual specialty",
  "Raised on a farm where the harvest sometimes harvested back",
  "Survivor of an orphan train, placed with a family that needed you for something specific",
  "Apprenticed to a locksmith who could open doors that weren't there",
  "Grew up serving as a living memory for an illiterate warlord—you know too much",
  "Former tender of a shrine to a forgotten god who started remembering",
  "Raised as part of a long-term experiment by an academy—you were the control group",
  "Worked as a food tester for a paranoid merchant who was right to be paranoid",
  "Grew up in a canyon town built into the walls, never touching the ground below",
  "Former caretaker of an ossuary where the bones occasionally rearranged themselves",
  "Raised by actors who never broke character, even at home",
  "Survived a fever that left you dead for three days according to the physician",
  "Apprenticed to a rope-maker whose rope always held—and sometimes held on its own",
  "Grew up in a community of shipbreakers who salvaged more than timber",
  "Former courier for a bank that dealt in currencies other than coin",
  "Raised in a household where a different set of rules applied after midnight",
  "Worked as a minder for a savant who could predict deaths but not prevent them",
  "Grew up the child of an executioner, inheritor of professional secrets and social isolation",
  "Former keeper of hunting hounds that tracked quarry no natural dog could sense",
  "Raised in a sealed community that was hiding from a war that ended a century ago",
  "Survivor of a fever ship, the only one who walked off alive at port",
  "Apprenticed to a cobbler who made shoes for clients with unusual feet",
  "Grew up in the basement of a gambling hall, learning odds and desperation",
  "Former assistant to a medium who was horrified when it started working",
  "Raised by a deaf-mute who communicated through a system only you understand",
  "Worked as a runner for a gossip network that toppled governments",
  "Grew up in a building converted from something older, something that still influenced dreams",
  "Former ward of a knight who was paying off an unspecified debt to your bloodline",
  "Raised in a community of beekeepers whose bees behaved with disturbing coordination",
  "Apprenticed to a midwife who served clients from both sides of the veil",
  "Survived being buried alive by grave robbers—something helped you dig out",
  "Former census-taker for a territory that included places and persons not entirely real",
  "Raised in an inn at a crossroads where three different worlds occasionally overlapped",
  "Worked as an assistant to a collector of impossible objects",
  "Grew up as a ward of the gallows, raised by the family of hangmen",
  "Former keeper of the last specimen of something that should have stayed extinct",
      // Third set of 50 backgrounds
      "Debtborn. Your family sold your future before you could walk",
      "Siltwalker. You know the tidal flats and what feeds there at night",
      "Bellringer. You rang the hours in a tower that kept strange time",
      "Oathbroken. You swore something terrible and failed to keep it",
      "Saltblood. The sea took your family but keeps spitting you back",
      "Threshold-child. You were born in a doorway between two places",
      "Ashkeeper. You tend the fires that must never go out",
      "Twice-drowned. You've died in water twice and returned both times",
      "Hollowed. Something lived inside you once. The space remains",
      "Coinbiter. You can taste the history of metal on your tongue",
      "Waxborn. They pulled you from a collapsed candle-maker's shop, alive",
      "Rootwalker. You know the paths beneath the forest floor",
      "Dustlung. The mines marked you, but you outlived the other workers",
      "Veilborn. Your mother died birthing you. She still visits",
      "Bonecarver. You learned your craft from the dead themselves",
      "Stormcalled. Lightning has struck near you seven times",
      "Mirrorwise. You learned things from your reflection it shouldn't know",
      "Chainsworn. You wear the broken links of your former bondage",
      "Plagueblessed. The sickness that killed thousands spared only you",
      "Namekeeper. You remember the true names of things that want to be forgotten",
      "Gallowsborn. Your mother was cut down still carrying you",
      "Duskwalker. You're most yourself in the hour between light and dark",
      "Fleshscribed. Someone wrote something on your skin you cannot read",
      "Hearthless. You've never had a home. Fires dim when you approach",
      "Wordbound. You made a promise to something that remembers perfectly",
      "Blackwater. You drank from a well you shouldn't have",
      "Loomtouched. You see the threads that connect living things",
      "Crowheart. The birds follow you. They're waiting for something",
      "Nightsoil. You know what people throw away and what it says about them",
      "Keykeeper. You guard doors. Some of them aren't visible",
      "Blightborn. You grew up on poisoned land and it grew into you",
      "Silence-sworn. You kept a vow of silence so long, words feel foreign",
      "Marrowdeep. You've been inside the bones of the earth",
      "Sundeath. You watched something kill the sun once. It came back different",
      "Threadcutter. You ended lives professionally, with ceremony",
      "Lastborn. You're the final child of a dying bloodline",
      "Wakeful. You haven't truly slept in years. Something waits in dreams",
      "Scar-reading. Your wounds tell stories to those who know the language",
      "Breathholder. You've learned to survive where air doesn't reach",
      "Omen-marked. Seers flinch when they look at you",
      "Twinless. Your other half died. You feel the absence like a limb",
      "Stone-listener. The walls speak to you of what they've witnessed",
      "Candle-counter. You measure your life in flames extinguished",
      "Doomtold. A prophecy names you. You don't know what it says",
      "Beastwise. Animals trust you more than people do. They're right to",
      "Pale-touched. You spent time somewhere the sun doesn't reach",
      "Blood-accountant. You know exactly what you owe and to whom",
      "Husk-dweller. You lived in the corpse of something massive",
      "Echo-born. You came back wrong, but you came back",
      "Endling. You're the last of something. You don't know what yet",
      // Fourth set of 250 backgrounds
      "Inkblood. Your family's history is tattooed across your skin",
      "Cradlerobbed. The fae left you in place of the child they took",
      "Godsforsaken. Every temple you enter falls silent",
      "Wreckwalker. You salvage what the storms bring to shore",
      "Bondsbroken. You killed someone you swore to protect",
      "Tongue-taken. You spoke something forbidden and lost your voice for years",
      "Crowfed. They left you for dead. The carrion birds disagreed",
      "Debt-inherited. Your ancestor's bargain came due in your generation",
      "Fog-found. You walked out of a mist with no memory of entering",
      "Ironsworn. A vow binds you tighter than any chain",
      "Maskborn. You've worn so many faces you've forgotten your own",
      "Northburnt. The cold took your fingers but taught you patience",
      "Oathkeeper. You fulfilled a promise that cost you everything",
      "Pit-raised. The fighting arenas were your schoolyard",
      "Questmarked. A dying stranger pressed a symbol into your palm",
      "Rootless. You've never slept in the same place twice by choice",
      "Saltcured. The ocean preserved you when it should have killed you",
      "Thornborn. The briars parted for your mother. You carry their mark",
      "Umbral. Your shadow moves a moment before you do",
      "Vaultborn. You were raised in a sealed bunker against a threat that never came",
      "Wormfed. You ate things in the dark times that still crawl in dreams",
      "Yearwalker. You experienced a year in a single night",
      "Zealbreaker. You destroyed what your family worshipped for generations",
      "Ashwalker. You wander the ruins of your burned homeland",
      "Blight-touched. Disease refuses to take you, but marks you still",
      "Chainbreaker. You led others to freedom and bear the scars",
      "Dawnchild. You were born at the exact moment of sunrise",
      "Edgewalker. You've balanced between life and death so long it feels normal",
      "Feastborn. Your birth was celebrated by a kingdom. Then the kingdom fell",
      "Graverobber. You know what the dead carry and where they rest",
      "Hellscarred. Something from below left its mark on your soul",
      "Iceblood. The cold doesn't touch you. Neither does warmth",
      "Jinxcarrier. Misfortune follows you but rarely strikes you directly",
      "Keystroke. You can open any lock given time. Some doors opened back",
      "Laughterborn. You were born during an execution. Your mother's",
      "Moonchild. You were born beneath a blood moon. Wolves remember",
      "Nightsinger. You learned songs that should only be sung in darkness",
      "Oracletouched. A seer held you as an infant and wept",
      "Plaguechild. Born during the dying time, you carry immunity and guilt",
      "Questioner. You extracted confessions professionally. Some were even true",
      "Runecarved. Someone inscribed power into your flesh without asking",
      "Stormborn. Thunder heralded your arrival. Lightning marked your path",
      "Tidechild. The sea rises when you're near",
      "Undertaker. You've buried more people than you've spoken to",
      "Venom-nursed. A serpent's bite as an infant changed you",
      "Wardslave. You were sold to protect someone else's child",
      "Xenolith. You remember a place that doesn't exist in this world",
      "Yeoman. You worked land that was never yours to own",
      "Zealot-raised. Faith was beaten into you before you could question",
      "Abyssgazer. You've looked into the void. Something looked back",
      "Bloodwriter. Your family recorded debts in their own veins",
      "Cageborn. You spent your first years in a cell",
      "Dustbreather. The desert winds carry your ancestors' whispers",
      "Emberkeeper. You tend flames that have burned for centuries",
      "Floodchild. Waters rose the day you were born and never fully receded",
      "Ghostkeeper. You maintain the shrines the living have forgotten",
      "Harvestborn. The fields gave up their dead the year you arrived",
      "Inkdrinker. You consumed forbidden texts. They consume you back",
      "Jarbound. Your soul was kept separate from your body for years",
      "Knifechild. You learned to cut before you learned to speak",
      "Loreburnt. You destroyed knowledge to protect the world from it",
      "Mirebred. The swamp people raised you in the spaces between",
      "Netherwalker. You've visited the lands of the dead and returned changed",
      "Omenborn. Your birth was preceded by impossible signs",
      "Pactchild. Your parents' deal included you before you existed",
      "Quicksilver. Mercury poisoning should have killed you. Instead it awakened something",
      "Relicbound. A holy object was fused with your body at birth",
      "Siegeborn. You emerged during the final assault. The walls fell after",
      "Truthseeker. You can taste deception. It's bitter",
      "Undercity. The sewers and catacombs were your first home",
      "Voidsick. You've traveled between worlds. The journey left marks",
      "Warchild. Battle was your lullaby, blood your first bath",
      "Xenophage. You've consumed the flesh of thinking beings to survive",
      "Yellowjacket. You worked the plague pits, collecting the dead",
      "Zodiacal. The stars spelled something at your birth. Astrologers argue what",
      "Altar-raised. You grew up as a temple's living sacrifice-in-waiting",
      "Bridgeburner. You've severed your connection to everyone you loved",
      "Covenbound. A circle of practitioners considers you their property",
      "Deathspeaker. The dying whisper secrets to you in their final moments",
      "Exorcised. Something was driven from you. Part of you went with it",
      "Fleshscribe. You learned to read the stories bodies tell",
      "Guildless. Every organization you've joined has expelled you",
      "Houndmaster. You raised the dogs that hunt you now",
      "Idolmaker. You crafted gods for others to worship",
      "Judged. A court declared you dead. You didn't cooperate",
      "Killcount. You know exactly how many. You can't forget",
      "Lockborn. You emerged from a sealed room no one knew existed",
      "Memorykeeper. You carry the dying thoughts of your entire village",
      "Nullborn. Magic slides off you like water. Mages find you disturbing",
      "Oldblood. Your lineage predates the current age",
      "Prophecyfed. You were raised on interpretations of what you'd become",
      "Quarantined. You spent years sealed away from the healthy",
      "Ransomchild. Your family paid for you. Then paid again. Then stopped",
      "Sewerking. The underground was your kingdom, rats your subjects",
      "Tattersoul. Your spirit is visibly damaged. Mystics flinch",
      "Undertow. You've been pulled beneath the waves more times than you can count",
      "Vigil-keeper. You've watched over the dying for so long, death knows your face",
      "Wetnurse. You fed noble children while your own starved",
      "Exileborn. Your parents were cast out. You've never known a homeland",
      "Yoke-scarred. The harness marks never fully healed",
      "Zerohour. You arrived precisely when the old world ended",
      "Ashenpriest. You served gods that have since been overthrown",
      "Bloodprice. Your family owes a debt that can only be paid in red",
      "Corpseflower. You grew up in a graveyard. The dead were kinder than the living",
      "Doomcrier. You announced deaths before they happened. They stopped listening",
      "Edgecrawler. You navigated the borders between territories nobody wanted",
      "Feverbred. Sickness shaped you in the womb",
      "Gallowsfruit. Born to a hanged mother, cut from the rope",
      "Heresyborn. Your very existence contradicts official doctrine",
      "Idolbreaker. You've smashed more gods than most people pray to",
      "Jailwife. You married into a prison. Escape wasn't an option",
      "Kindling. You were meant to be burned. The fire refused",
      "Lithborn. You emerged from stone, or so the quarry workers claim",
      "Marrowthief. You've stolen bones from sacred ossuaries",
      "Namegiven. A dying god granted you their title",
      "Outlander. Your people don't appear on any census",
      "Prisonship. Born on a vessel of criminals bound for exile",
      "Quartermaster. You've distributed rations during sieges and famines",
      "Ritualscarred. A ceremony went wrong. You're what emerged",
      "Stillborn. You were dead for the first hour of your life",
      "Titheborn. You were given to the church as payment",
      "Unbaptized. No god has claimed you. That may be a blessing",
      "Verminlord. The pests answer to you. You're not sure why",
      "Waifborn. You've been unclaimed since your first breath",
      "Executioner's child. You inherited the hood and the isolation",
      "Yearling. You age differently than you should",
      "Zenith-touched. You were born at the sun's highest point. Heat doesn't bother you",
      "Anvilstruck. A blacksmith's accident marked you for life",
      "Bargechild. You were born on moving water and feel wrong on land",
      "Cryptkeeper. The dead rest easier when you tend them",
      "Dredger. You pulled things from rivers. Not all of them were objects",
      "Emberwitch. Fire dances for you. It's cost you homes",
      "Finderkeeper. Lost things appear near you. Not always good things",
      "Griefmonger. You've made a living from others' sorrow",
      "Halfdrowned. Water fills your lungs in dreams but never kills you",
      "Inheritrix. You received something terrible from someone you never met",
      "Justiciar. You've executed judgment outside any law",
      "Keeperless. Every protector you've had has died violently",
      "Lotcaster. You've decided fates with dice and bones",
      "Mindscarred. Something rewrote parts of your memory",
      "Nightworker. You've only ever labored after sunset",
      "Outbound. You carry a curse that prevents you from returning home",
      "Pallbearer. You've carried more dead than you can name",
      "Quickened. Something dead stirred in your presence",
      "Residue. A spell was cast on you. Only the side effects remain",
      "Spireborn. You were raised in a tower. The ground still feels foreign",
      "Threshold. You've died on doorsteps. Always pulled back",
      "Underbridge. Trolls raised you. That's not a metaphor",
      "Veinreader. You learned fortune-telling from blood patterns",
      "Wandersoul. Your spirit slips free when you sleep",
      "Exanguinated. You've been drained to the point of death. Multiple times",
      "Yarnsinger. Your grandmother wove prophecies. You inherited half the gift",
      "Zephyrchild. The wind speaks to you in a language you almost understand",
      "Anchorless. You've never been bound to a place, person, or purpose",
      "Brinedrinker. Saltwater sustains you. Fresh water tastes wrong",
      "Clockwatcher. Time moves strangely around you",
      "Dirtborn. You emerged from a grave that wasn't yours",
      "Eyeless. You see, but not with your eyes",
      "Fortunefed. Gamblers touched you for luck. It never helped them",
      "Gloomwalker. Shadows feel like home",
      "Heartless. An organ is missing. You function anyway",
      "Irontongue. You can't lie. You've tried",
      "Journeyman. You've mastered no trade but sampled dozens",
      "Keyholder. Doors unlock when you need them to",
      "Lambswool. You were raised among sheep. Wolves followed",
      "Mossback. The forest grew over your childhood home with you inside",
      "Nightingale. Your voice carries secrets you don't consciously know",
      "Orchard-kept. The fruit trees sheltered you when humans wouldn't",
      "Pinpricked. Fae needles in your cradle. You've been strange since",
      "Quillborn. Your first cry drew blood from everyone present",
      "Rootbound. Plants grow where you've slept",
      "Skinturner. You've worn other forms. They're getting harder to shed",
      "Twiceborn. You have two birthdays. You only remember one",
      "Unseen. People forget you moments after you leave",
      "Vineblood. The wine harvest speaks to you",
      "Wellchild. You were found in a well, origin unknown",
      "Excommunicate. Cast out from a faith that still haunts you",
      "Yearkeeper. You've counted time for those who couldn't",
      "Zenithal. You cast no shadow at noon",
      "Alchemy-raised. You grew up among bubbling experiments and failed transmutations",
      "Battleborn. Your first sight was warfare. Your first sound was screaming",
      "Cairnkeeper. You stack stones for the dead and remember their names",
      "Dolorous. Grief follows you. Some say you attract it",
      "Ember-eye. Fire flickers in your gaze when you're angry",
      "Foresworn. You broke an oath so thoroughly the gods noticed",
      "Gravemender. You repair what body snatchers disturb",
      "Heirloom. You're the last keeper of something important",
      "Inkskin. Stories are written across your body in languages you're learning",
      "Judgement-escaped. You were sentenced. The method of execution failed",
      "Knotworker. You understand bindings, ties, and connections",
      "Lamentor. You sing the songs that help the dying let go",
      "Mooncalf. Born wrong, they said. Time proved them wronger",
      "Nethertouched. Something from below recognizes you",
      "Oathsmith. You forge promises into binding contracts",
      "Parchmentblood. Your family's records go back further than history",
      "Quarry-escaped. You were hunted for sport. You survived",
      "Remnant. You're all that remains of something larger",
      "Stoneheart. Emotions come slowly to you, if at all",
      "Tinderbox. Fire starts easily around you. Too easily",
      "Unmoored. You drift between places without meaning to",
      "Vaultkeeper. You guard something you've never been allowed to see",
      "Woundweaver. You understand how bodies break and mend",
      "Expunged. Records of your existence have been systematically destroyed",
      "Yawnchild. Born during the great sleep, when the whole town wouldn't wake",
      "Zeropoint. Magic has trouble finding you",
      "Ashwielder. You've burned enough villages to know the smell",
      "Blackthumb. Nothing you plant survives. Things you didn't plant flourish",
      "Cavernborn. Daylight still hurts your eyes",
      "Deathmask. You've worn the faces of the departed",
      "Echokeeper. You remember sounds from before you were born",
      "Frostburnt. The cold marked you. You mark it back",
      "Galeborn. You arrived during the hurricane. The wind still knows you",
      "Hushchild. Silence follows you into rooms",
      "Ironwilled. Compulsions slide off your mind like oil",
      "Jetsam. The sea keeps returning you to shore",
      "Kinslayer. Family blood stains your hands",
      "Loamborn. You grew up half-buried in earth",
      "Mirrormarked. Your reflection knows things you don't",
      "Nightblind. You see perfectly in darkness, poorly in light",
      "Outskirter. You've lived at the edges of a dozen communities",
      "Plaguemask. You wore the beak during the dying years",
      "Quickfoot. You've outrun things that shouldn't be outrunnable",
      "Riftwalker. You've stepped through tears in reality",
      "Soulcounted. A census-taker marked something strange about you",
      "Threshold-born. You were born neither inside nor out",
      "Undergrowth. The weeds hid you when you needed hiding",
      "Venomblood. Poison runs in your veins. You've learned to use it",
      "Warprize. You were taken as a trophy. You escaped as a threat",
      "Exhumed. You've been buried and dug up. Not necessarily in that order",
      "Yieldless. Torture couldn't break you. The scars remain",
      "Zincskin. Metal objects leave marks on your flesh",
      "Abacus-mind. Numbers make more sense than people",
      "Breathstealer. You were born with the cord around your neck. You survived",
      "Coalwalker. Fire can't burn you. Heat still can",
      "Daggertongue. Your words wound as effectively as blades",
      "Eavesdweller. You grew up in the spaces under roofs",
      "Flamekeeper. You tend fires that must never be extinguished",
      "Gutterborn. The streets raised you harsher than any parent could",
      "Hexborn. Witches marked you in the womb",
      "Idolatrix. You've been worshipped. You know what it costs",
      "Jackdaw. You collect shiny things. Some collect you back",
      "Keeperless. No god has claimed you, despite many attempts",
      "Lychgate. You were born in a churchyard threshold",
      "Millstone. Heavy burdens are your inheritance",
      "Nightjar. You've always been more awake after sunset",
      "Ossuary-born. Your first bed was among the bones of saints",
      "Penumbral. You exist best in partial shadow",
      "Quenchless. Thirst drives you. Nothing satisfies it completely",
      "Reliquary. You carry pieces of the dead within you",
      "Scapegoat. You've borne punishment for others' sins so often it feels natural",
    ],
  },
  {
    id: "shadowdark",
    name: "Shadowdark",
    dieSize: 20,
    backgrounds: [
      "Urchin. You grew up in the merciless streets of a large city",
      "Wanted. There's a price on your head, but you have allies",
      "Cult Initiate. You know blasphemous secrets and rituals",
      "Thieves' Guild. You have connections, contacts, and debts",
      "Banished. Your people cast you out for supposed crimes",
      "Orphaned. An unusual guardian rescued and raised you",
      "Wizard's Apprentice. You have a knack and eye for magic",
      "Jeweler. You can easily appraise value and authenticity",
      "Herbalist. You know plants, medicines, and poisons",
      "Barbarian. You left the horde, but it never quite left you",
      "Mercenary. You fought friend and foe alike for your coin",
      "Sailor. Pirate, privateer, or merchant — the seas are yours",
      "Acolyte. You're well trained in religious rites and doctrines",
      "Soldier. You served as a fighter in an organized army",
      "Ranger. The woods and wilds are your true home",
      "Scout. You survived on stealth, observation, and speed",
      "Minstrel. You've traveled far with your charm and talent",
      "Scholar. You know much about ancient history and lore",
      "Noble. A famous name has opened many doors for you",
      "Chirurgeon. You know anatomy, surgery, and first aid",
    ],
  },
  {
    id: "diablerie",
    name: "Cursed Scroll: Diablerie",
    dieSize: 20,
    backgrounds: [
      "Hermit. The wilds (and its creatures) are your family",
      "Outcast. You were thrown out for real or supposed crimes",
      "Woodborn. They found you in the hollow of an oak tree",
      "Amnesiac. Your past is a haze, but some memories return",
      "Haunted. A restless spirit wants something from you",
      "Fugitive. An anonymous savior helped you disappear",
      "Feytouched. A fairy befriended you in your childhood",
      "Witchborn. They burned your mother, but spared you",
      "Forager. You know how to find the edible and the deadly",
      "Redeemer. You must redeem the name of your kin",
      "Marked. You carry an eldritch mark. Is it a curse, or a gift?",
      "Sacrifice. You were to be ritually sacrificed, but escaped",
      "Marooned. They left you behind, but you refused to die",
      "Fallen. You fell from grace. Will you atone, or embrace it?",
      "Drawn. You hear a whispered call and follow it",
      "Ascetic. People fear you, but seek out your guidance",
      "Wolfchild. Long ago, you walked into town wearing pelts",
      "Healer. You understand how life and death intertwine",
      "Chosen. An eldritch being selected you for a purpose",
      "Demonborn. An ancestor of yours is a powerful demon",
    ],
  },
  {
    id: "midnight-sun",
    name: "Cursed Scroll: Midnight Sun",
    dieSize: 20,
    backgrounds: [
      "Freed. You were a thrall, but escaped or won your freedom",
      "Displaced. You fled after a rival jarl attacked your village",
      "Criminal. You were exiled from your village for a crime",
      "Drifter. You have not yet found a jarl worthy of your loyalty",
      "Crop Farmer. You toil in the earth and know all plants",
      "Livestock Farmer. You have intuition about all animals",
      "Hunter. You know how to move quietly in the wilds",
      "Fisher. You know all the sea creatures and legends",
      "Enforcer. You enforce the jarl's law in your village",
      "Trader. You have mercantile connections in every village",
      "Crafter. You can make and fix any utilitarian item",
      "Bowyer. You can make and fix any bow or arrow",
      "Seer's Apprentice. You know some of the mystic arts",
      "Shipwright. You know how to build and repair longboats",
      "Blacksmith. Weapons, armor, horseshoes; you do it all",
      "Far Traveler. You know many distant people and customs",
      "Skald. You are a poet and know all the ancient ballads",
      "Heroborn. You are the descendant of a famous warrior",
      "Nobleborn. You are the child of a 1d6: 1-5. jarl, 6. king",
      "God's Blood. You are descended from a god; it marks you",
    ],
  },
];

function BackgroundGenerator() {
  const [selectedTable, setSelectedTable] = createSignal<TableId>("custom");
  const [roll, setRoll] = createSignal<number | null>(null);
  const [background, setBackground] = createSignal<string | null>(null);

  const currentTable = () => tables.find((t) => t.id === selectedTable())!;

  const rollBackground = () => {
    const table = currentTable();
    const newRoll = Math.floor(Math.random() * table.dieSize) + 1;
    setRoll(newRoll);
    setBackground(table.backgrounds[newRoll - 1]);
  };

  const handleTableChange = (tableId: TableId) => {
    setSelectedTable(tableId);
    setRoll(null);
    setBackground(null);
  };

  return (
    <div class="space-y-6">
      <section class="space-y-2">
        <h1 class="mb-8">Background Generator</h1>
        <p>
          Select a table and roll to generate a random background for your
          character.
        </p>
      </section>

      <section class="space-y-4">
        <div class="flex gap-2">
          <For each={tables}>
            {(table) => (
              <button
                onClick={() => handleTableChange(table.id)}
                class={`px-4 py-2 border cursor-pointer ${
                  selectedTable() === table.id
                    ? "border-stone-600 bg-stone-200"
                    : "border-stone-400 bg-stone-100 hover:bg-stone-200"
                }`}
              >
                {table.name}
              </button>
            )}
          </For>
        </div>

        <button
          onClick={rollBackground}
          class="px-4 py-2 border border-stone-400 bg-stone-100 hover:bg-stone-200 cursor-pointer"
        >
          Roll d{currentTable().dieSize}
        </button>

        {roll() !== null && (
          <div class="p-4 border border-stone-300 bg-stone-100">
            <p class="text-sm text-stone-500 mb-2">Rolled: {roll()}</p>
            <p class="text-lg">{background()}</p>
          </div>
        )}
      </section>
    </div>
  );
}
