/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SheetRouteImport } from './routes/sheet'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as GeneratorRouteImport } from './routes/generator'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RulesVariantRouteImport } from './routes/rules_.variant'
import { Route as PagesSlugRouteImport } from './routes/pages/$slug'
import { Route as GenerateBackgroundRouteImport } from './routes/generate/background'
import { Route as ApiSyncRouteImport } from './routes/api/sync'

const SheetRoute = SheetRouteImport.update({
  id: '/sheet',
  path: '/sheet',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const GeneratorRoute = GeneratorRouteImport.update({
  id: '/generator',
  path: '/generator',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesVariantRoute = RulesVariantRouteImport.update({
  id: '/rules_/variant',
  path: '/rules/variant',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesSlugRoute = PagesSlugRouteImport.update({
  id: '/pages/$slug',
  path: '/pages/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerateBackgroundRoute = GenerateBackgroundRouteImport.update({
  id: '/generate/background',
  path: '/generate/background',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSyncRoute = ApiSyncRouteImport.update({
  id: '/api/sync',
  path: '/api/sync',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/generator': typeof GeneratorRoute
  '/rules': typeof RulesRoute
  '/sheet': typeof SheetRoute
  '/api/sync': typeof ApiSyncRoute
  '/generate/background': typeof GenerateBackgroundRoute
  '/pages/$slug': typeof PagesSlugRoute
  '/rules/variant': typeof RulesVariantRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/generator': typeof GeneratorRoute
  '/rules': typeof RulesRoute
  '/sheet': typeof SheetRoute
  '/api/sync': typeof ApiSyncRoute
  '/generate/background': typeof GenerateBackgroundRoute
  '/pages/$slug': typeof PagesSlugRoute
  '/rules/variant': typeof RulesVariantRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/generator': typeof GeneratorRoute
  '/rules': typeof RulesRoute
  '/sheet': typeof SheetRoute
  '/api/sync': typeof ApiSyncRoute
  '/generate/background': typeof GenerateBackgroundRoute
  '/pages/$slug': typeof PagesSlugRoute
  '/rules_/variant': typeof RulesVariantRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/generator'
    | '/rules'
    | '/sheet'
    | '/api/sync'
    | '/generate/background'
    | '/pages/$slug'
    | '/rules/variant'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/generator'
    | '/rules'
    | '/sheet'
    | '/api/sync'
    | '/generate/background'
    | '/pages/$slug'
    | '/rules/variant'
  id:
    | '__root__'
    | '/'
    | '/generator'
    | '/rules'
    | '/sheet'
    | '/api/sync'
    | '/generate/background'
    | '/pages/$slug'
    | '/rules_/variant'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GeneratorRoute: typeof GeneratorRoute
  RulesRoute: typeof RulesRoute
  SheetRoute: typeof SheetRoute
  ApiSyncRoute: typeof ApiSyncRoute
  GenerateBackgroundRoute: typeof GenerateBackgroundRoute
  PagesSlugRoute: typeof PagesSlugRoute
  RulesVariantRoute: typeof RulesVariantRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/sheet': {
      id: '/sheet'
      path: '/sheet'
      fullPath: '/sheet'
      preLoaderRoute: typeof SheetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generator': {
      id: '/generator'
      path: '/generator'
      fullPath: '/generator'
      preLoaderRoute: typeof GeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules_/variant': {
      id: '/rules_/variant'
      path: '/rules/variant'
      fullPath: '/rules/variant'
      preLoaderRoute: typeof RulesVariantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/$slug': {
      id: '/pages/$slug'
      path: '/pages/$slug'
      fullPath: '/pages/$slug'
      preLoaderRoute: typeof PagesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generate/background': {
      id: '/generate/background'
      path: '/generate/background'
      fullPath: '/generate/background'
      preLoaderRoute: typeof GenerateBackgroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sync': {
      id: '/api/sync'
      path: '/api/sync'
      fullPath: '/api/sync'
      preLoaderRoute: typeof ApiSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GeneratorRoute: GeneratorRoute,
  RulesRoute: RulesRoute,
  SheetRoute: SheetRoute,
  ApiSyncRoute: ApiSyncRoute,
  GenerateBackgroundRoute: GenerateBackgroundRoute,
  PagesSlugRoute: PagesSlugRoute,
  RulesVariantRoute: RulesVariantRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/solid-start'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
